DROP TABLE IF EXISTS Bank_Transaction;  
CREATE TABLE Bank_Transaction (  
REFERENCE_NO INT PRIMARY KEY,  
ACCOUNT_NO VARCHAR(22) NOT NULL,
START_BALANCE DOUBLE NOT NULL,
MUTATION VARCHAR(10) NOT NULL,
DESCRIPTION  VARCHAR(50),
END_BALANCE DOUBLE NOT NULL
);